#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building xfl.ls -> xfl.js ..."
./node_modules/.bin/lsc -cp --no-header src/xfl.ls > dist/xfl.js
echo "minify xfl.js -> xfl.min.js ..."
./node_modules/.bin/uglifyjs dist/xfl.js > dist/xfl.min.js

echo "copy dist to web ..."
rm -rf web/static/assets/lib/@plotdb/xfl/dev/
mkdir -p web/static/assets/lib/@plotdb/xfl/dev/
cp -R dist/* web/static/assets/lib/@plotdb/xfl/dev/

echo "done."
